[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "http://*"
  to = "https://veradia.org/:splat"
  status = 301
  force = true